name: CI

on: [push, pull_request]

jobs:

  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome, firefox]  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven
        run: mvn package
      - name: Push to Quay.io
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: konveyor/controls-keycloak-theme
          dockerfile: Dockerfile
          snapshot: false
          tags: "test"    
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: false
          start: yarn run keycloak:start
          wait-on: 'http://localhost:8080/auth'
          wait-on-timeout: 120
          config: pageLoadTimeout=100000,baseUrl=http://localhost:8080
          browser: ${{ matrix.browser }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: e2e-screenshots-${{ matrix.os }}-${{ matrix.browser }}
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: e2e-videos-${{ matrix.os }}-${{ matrix.browser }}
          path: cypress/videos
      - uses: codecov/codecov-action@v1
        with:
          flags: e2etests  
