name: CI

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome]
        # browser: [chrome, firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven
        run: mvn package
      - name: Create image
        uses: elgohr/Publish-Docker-Github-Action@3.02
        with:
          name: konveyor/tackle-keycloak-theme
          dockerfile: Dockerfile
          snapshot: false
          tags: "test"
          no_push: true
      - name: Start keycloak
        run: |
          docker network create konveyor

          docker run -d --name keycloak --network konveyor --network-alias keycloak -p 8080:8080 \
          -e KEYCLOAK_USER=admin \
          -e KEYCLOAK_PASSWORD=admin \
          -e DB_VENDOR=h2 \
          konveyor/tackle-keycloak-theme:test

          sleep 5s && docker logs keycloak
      - name: Keycloak Admin CLI
        uses: carlosthe19916/keycloak-action@0.4
        with:
          server: http://localhost:8080/auth
          username: admin
          password: admin
          kcadm: update realms/master -s loginTheme=konveyor
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: false
          wait-on: "http://localhost:8080/auth"
          wait-on-timeout: 120
          config: pageLoadTimeout=100000,baseUrl=http://localhost:8080
          browser: ${{ matrix.browser }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: e2e-screenshots-${{ matrix.os }}-${{ matrix.browser }}
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: e2e-videos-${{ matrix.os }}-${{ matrix.browser }}
          path: cypress/videos
