name: CI

on: [push, pull_request]

jobs:

  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome, firefox]
    services:
      keycloak:
        image: quay.io/keycloak/keycloak:12.0.1
        ports:
          - 8180:8080
        env:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
        volumes:
          # - ${{ github.workspace }}/target:/opt/jboss/keycloak/standalone/deployments
          - /opt/jboss/keycloak:/opt/jboss/keycloak
        options: >-
          --health-cmd "curl --fail http://localhost:8080/auth || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven
        run: mvn package
      - name: Keycloak Admin CLI
        uses: carlosthe19916/keycloak-action@master
        with:
          server: http://keycloak:8080/auth
          username: admin
          password: admin
          # jboss-cli: -c --controller=keycloak:9990 --command="deploy ./target/controls-keycloak-theme.jar"
          kcadm: update realms/master -s loginTheme=konveyor
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: false
          start: yarn run start
          wait-on-timeout: 120
          config: pageLoadTimeout=100000,baseUrl=http://localhost:8180
          browser: ${{ matrix.browser }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: e2e-screenshots-${{ matrix.os }}-${{ matrix.browser }}
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: e2e-videos-${{ matrix.os }}-${{ matrix.browser }}
          path: cypress/videos
      - uses: codecov/codecov-action@v1
        with:
          flags: e2etests  
